name: dspace-handle-server

services:

  dspace-handle-server:
    container_name: dspace-handle-server
    image: ${IMAGE_TAG}
    build:
      context: .
      args:
        - ALPINE_VERSION=3.23.3
        - OPT_PACKAGES=${OPT_PACKAGES}
        - HANDLE_SOFTWARE_VER=${HANDLE_SOFTWARE_VER}
        - JAVA_VERSION=${JAVA_VERSION}
        - DSPACE_REMOTE_HANDLE_RESOLVER_ARTIFACT=${DSPACE_REMOTE_HANDLE_RESOLVER_ARTIFACT}
        - HANDLE_SERVER_DIR=${HANDLE_SERVER_DIR}
        - SERVER_NAME=${SERVER_NAME}
        - PRIMARY_SERVER=${PRIMARY_SERVER}
        - DUAL_STACK_SERVER=${DUAL_STACK_SERVER}
        - IP_ADDRESS=${IP_ADDRESS}
        - BIND_IP=${BIND_IP}
        - TCP_UDP_PORT=${TCP_UDP_PORT}
        - HTTP_PORT=${HTTP_PORT}
        - LOG_ACCESS=${LOG_ACCESS}
        - LOG_ROTATION_FREQUENCY_SHORT=${LOG_ROTATION_FREQUENCY_SHORT}
        - SITE_VERSION_SERIAL_NUMBER=${SITE_VERSION_SERIAL_NUMBER}
        - SERVER_DESCRIPTION=${SERVER_DESCRIPTION}
        - ORG_NAME=${ORG_NAME}
        - ORG_CONTACT_PERSON=${ORG_CONTACT_PERSON}
        - ORG_CONTACT_PHONE=${ORG_CONTACT_PHONE}
        - ORG_CONTACT_EMAIL=${ORG_CONTACT_EMAIL}
        - DISABLE_UDP=${DISABLE_UDP}
        - ENCRYPT_SERVER_KEY=${ENCRYPT_SERVER_KEY}
        - ENCRYPT_ADMIN_KEY=${ENCRYPT_ADMIN_KEY}
        - PREFIXES_ADMINS=${PREFIXES_ADMINS}
        - HANDLE_PREFIXES=${HANDLE_PREFIXES}
        - LOG_ROTATION_FREQUENCY_LONG=${LOG_ROTATION_FREQUENCY_LONG}
        - DSPACE_SERVER_URLS=${DSPACE_SERVER_URLS}
        - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${TCP_UDP_PORT}:${TCP_UDP_PORT}
    environment:
      BIND_IP: ${BIND_IP}
      HTTP_PORT: ${HTTP_PORT}
      LOG_ACCESS: ${LOG_ACCESS}
      TCP_UDP_PORT: ${TCP_UDP_PORT}
      PREFIXES_ADMINS: ${PREFIXES_ADMINS}
      HANDLE_PREFIXES: ${HANDLE_PREFIXES}
      LOG_ROTATION_FREQUENCY_LONG: ${LOG_ROTATION_FREQUENCY_LONG}
      DSPACE_SERVER_URLS: ${DSPACE_SERVER_URLS}
      JAVA_OPTS: ${JAVA_OPTS}
      HANDLE_SOFTWARE_VER: ${HANDLE_SOFTWARE_VER}
      HANDLE_SERVER_DIR: ${HANDLE_SERVER_DIR}
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - logs:/${HANDLE_SERVER_DIR}/${SERVER_NAME}/logs

volumes:
  logs:
    driver: local

