ARG ALPINE_VERSION

FROM alpine:${ALPINE_VERSION}

ARG OPT_PACKAGES
ARG HANDLE_SOFTWARE_VER
ARG JAVA_VERSION
ARG DSPACE_REMOTE_HANDLE_RESOLVER_ARTIFACT
ARG HANDLE_SERVER_DIR
ARG SERVER_NAME

# ==== HANDLE SERVER SETUP ====
ARG PRIMARY_SERVER
ARG DUAL_STACK_SERVER
ARG IP_ADDRESS
ARG BIND_IP
ARG TCP_UDP_PORT
ARG HTTP_PORT
ARG LOG_ACCESS
ARG LOG_ROTATION_FREQUENCY_SHORT
ARG SITE_VERSION_SERIAL_NUMBER
ARG SERVER_DESCRIPTION
ARG ORG_NAME
ARG ORG_CONTACT_PERSON
ARG ORG_CONTACT_PHONE
ARG ORG_CONTACT_EMAIL
ARG DISABLE_UDP
ARG ENCRYPT_SERVER_KEY
ARG ENCRYPT_ADMIN_KEY

ARG PREFIXES_ADMINS
ARG HANDLE_PREFIXES
ARG LOG_ROTATION_FREQUENCY_LONG
ARG DSPACE_SERVER_URLS
ARG JAVA_OPTS
# ==== HANDLE SERVER SETUP ====

ENV LC_ALL="en_US.UTF-8"
ENV LANG="en_US.UTF-8"
ENV TZ="America/Chicago"

# ==== configurable settings in config.dct ====
ENV BIND_IP=${BIND_IP}
ENV HTTP_PORT=${HTTP_PORT}
ENV LOG_ACCESS=${LOG_ACCESS}
ENV TCP_UDP_PORT=${TCP_UDP_PORT}
ENV PREFIXES_ADMINS=${PREFIXES_ADMINS}
ENV HANDLE_PREFIXES=${HANDLE_PREFIXES}
ENV LOG_ROTATION_FREQUENCY_LONG=${LOG_ROTATION_FREQUENCY_LONG}
ENV DSPACE_SERVER_URLS=${DSPACE_SERVER_URLS}
ENV JAVA_OPTS=${JAVA_OPTS}
# ==== configurable settings in config.dct ====

ENV HANDLE_SOFTWARE_VER=${HANDLE_SOFTWARE_VER}
ENV HANDLE_SERVER_DIR={HANDLE_SERVER_DIR}
ENV SERVER_NAME={SERVER_NAME}

# Install basic packages :
RUN apk update && apk upgrade && \
    apk add --no-cache tzdata ca-certificates openjdk${JAVA_VERSION}-jre-headless ${OPT_PACKAGES} && \
    update-ca-certificates && \
    rm -rf /var/cache/apk/*

# Install and configure handle-server :
RUN mkdir -p /${HANDLE_SERVER_DIR}/${SERVER_NAME}/

COPY handle-${HANDLE_SOFTWARE_VER} /${HANDLE_SERVER_DIR}/handle-${HANDLE_SOFTWARE_VER}

RUN rm -f /${HANDLE_SERVER_DIR}/handle-${HANDLE_SOFTWARE_VER}/bin/hdl

COPY ${DSPACE_REMOTE_HANDLE_RESOLVER_ARTIFACT} /${HANDLE_SERVER_DIR}/handle-${HANDLE_SOFTWARE_VER}/lib/
COPY hdl /${HANDLE_SERVER_DIR}/handle-${HANDLE_SOFTWARE_VER}/bin/

# Generate hdl setup server answer file :
RUN ANSWER_FILE="/${HANDLE_SERVER_DIR}/answer-file.txt"
    echo ${PRIMARY_SERVER} >> ${ANSWER_FILE} && \
    echo ${DUAL_STACK_SERVER} >> ${ANSWER_FILE} && \
    echo ${IP_ADDRESS} >> ${ANSWER_FILE} && \
    echo ${BIND_IP} >> ${ANSWER_FILE} && \
    echo ${TCP_UDP_PORT} >> ${ANSWER_FILE} && \
    echo ${HTTP_PORT} >> ${ANSWER_FILE} && \
    echo ${LOG_ACCESS} >> ${ANSWER_FILE} && \
    echo ${LOG_ROTATION_FREQUENCY_SHORT} >> ${ANSWER_FILE} && \
    echo ${SITE_VERSION_SERIAL_NUMBER} >> ${ANSWER_FILE} && \
    echo ${SERVER_DESCRIPTION} >> ${ANSWER_FILE} && \
    echo ${ORG_NAME} >> ${ANSWER_FILE} && \
    echo ${ORG_CONTACT_PERSON} >> ${ANSWER_FILE} && \
    echo ${ORG_CONTACT_PHONE} >> ${ANSWER_FILE} && \
    echo ${ORG_CONTACT_EMAIL} >> ${ANSWER_FILE} && \
    echo ${DISABLE_UDP} >> ${ANSWER_FILE} && \
    echo ${ENCRYPT_SERVER_KEY} >> ${ANSWER_FILE} && \
    echo ${ENCRYPT_ADMIN_KEY} >> ${ANSWER_FILE} && \
    cat ${ANSWER_FILE}

# Configure handle server configs :
RUN rm -rf /${HANDLE_SERVER_DIR}/${SERVER_NAME}/* && \
    /${HANDLE_SERVER_DIR}/handle-${HANDLE_SOFTWARE_VER}/bin/hdl-setup-server \
    /${HANDLE_SERVER_DIR}/${SERVER_NAME} < ${ANSWER_FILE} && \
    rm -f /${HANDLE_SERVER_DIR}/${SERVER_NAME}/config.dct && \
    mkdir -p /${HANDLE_SERVER_DIR}/${SERVER_NAME}/logs

COPY config.dct /${HANDLE_SERVER_DIR}/${SERVER_NAME}/
COPY log4j2-handle-plugin.xml /${HANDLE_SERVER_DIR}/${SERVER_NAME}/
COPY handle-dspace-plugin.cfg /${HANDLE_SERVER_DIR}/${SERVER_NAME}/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /${HANDLE_SERVER_DIR}/${SERVER_NAME}

ENTRYPOINT ["entrypoint.sh"]

